### ISSUE TITLE
Has anyone created a dashboard for cloud custodian?

### ISSUE THREAD

**Issue by twitherspoon** [capitalone/cloud-custodian#1136]
We are looking to use Cloud Custodian to provide governance and management of over ~50 to ~70 AWS accounts. This will cover many different teams and groups across the enterprise. I foresee the policies we create will be used to tag/notify when resources are out of compliance and some will actually take actions like the stop and starting of an EC2 instances when they go in and out of compliance. We will also provided services like offhours scheduling and such.

All of of that is great and possible with Cloud Custodian. So my question is has anyone created an accompanying dashboard that teams and owners of individual AWS accounts can go view to see things like (just examples, but I'm guessing we will need more things):
- Number of instances out of compliance
- Number of instances tagged for stopping or termination
- Number of instances stopped or terminated b/c of compliance
- Number of <fill-in-the-blank> resources out of compliance

I'm thinking we need some sort of reporting or dashboard so account owners can see how things are in their account and what actions we have taken on their behalf.

Thanks

**Comment by JohnTheodore** [comment]
There is no dashboard to my knowledge. AWS Config looks like it could fill parts of that role one day, but it's still an early product from AWS and doesn't support a lot of service types, and you can't filter by resources you own easily, etc.

You can pull all the data from s3 or cloudwatch for what changed and make some passive UI out of that. We'd help you figure things out too if you want, join gitter.

**Comment by twitherspoon** [comment]
Sounds good. Let me know how to join.

**Comment by kapilt** [comment]
We do have a few dashboards available that capture those metrics, and more on the way. 

First if you pass -m on the custodian cli, it will output cloudwatch metrics into the target account. Cloudwatch dashboards can be used to construct some metrics dashboards on a per account basis, this is a usable baseline but suboptimal imo due to the lack of api on cloudwatch dashboard (manual work per account, plus adjust per policy changes). 

Second, in our tools subdirectory on a git checkout we have c7n_indexer that will aggregate all custodian cloudwatch metrics across multiple accounts into an influxdb that you can drop grafana on top of, it allows rollup across subsets of accounts, albeit with an assumption of consistent policy names.

We've got a few more items on the backlog for the indexer (elasticsearch support, additional ux/ui) per other open issues.

wrt to joining gitter, https://gitter.im/capitalone/cloud-custodian

**Comment by kumarsiyer** [comment]
cool, will explore this option :)
> Second, in our tools subdirectory on a git checkout we have c7n_indexer that will aggregate all custodian cloudwatch metrics across multiple accounts into an influxdb that you can drop grafana on top of, it allows rollup across subsets of accounts, albeit with an assumption of consistent policy names.

**Comment by twitherspoon** [comment]
Thanks @kapilt and @JohnTheodore. I'll take a look at the indexer. As for the cloudwatch metrics I don't think that has the detail I'm looking for b/c it only provides me raw numbers, but I think if I can use the logs that are stored into S3 thats what will get me there. I'm thinking I need to link the compliance rules and checks to the actual resources that are effected by those rules. Something like instance i-abcdefghi is out of compliance and will be stopped on 5/12/2017. And I need to allow teams to sort or filter by their instances and resources and suppress the things they don't necessarily care about.

I joined gitter. Great group and already seeing a lot of good questions and information come across.
