### ISSUE TITLE
Defining lambda timeout for custodian rule

### ISSUE THREAD

**Issue by jsmartin** [capitalone/cloud-custodian#1145]
One of my custodian rules is taking longer than 60 seconds (tag validation on S3 buckets) and is causing custodian to fail.  Where in custodian do I set the timeout for the lambda function that gets associated with the rule?

**Comment by cplee** [comment]
Timeout ought to be configured as a passthrough configuration under `mode`.

**Comment by kapilt** [comment]
fixed in 0.8.24, `timeout` can now be specified under `mode`

**Comment by tmxak** [comment]
Hi @kapilt 
Here is one of the policies that we use 
`policies:
- name: tag-tables
  resource: dynamodb-table
  description: |
    Detect when a new DynamoDB Table is created and mark it for deletion
  mode:
    role: arn:aws:iam::286420114124:role/c7n_lambda_role
    type: cloudtrail
    events:
      - CreateTable
    timeout: 180
  actions:
  - type: mark-for-op
    tag: CustodianMarkForDelete
    msg: "Will be deleted: {action_date}"
    op: delete
    days: 2` 
I want to tag table after creation, But I'm getting the error in CloudWatch:
`Resource Tag Errors {'arn:aws:dynamodb:eu-central-1:2123xxxxxxxx:table/qwerty': 'ResourceNotFoundException'}`
Because it tries to list tags on resource that is still in creation state. The arn of the resource is right. I think that timeout is not working properly. Could you check it please?

**Comment by kapilt** [comment]
@tmxak dynamodb tables can't be tagged on create, timeout is the max execution time of the lambda, ie if its was processing lots of resources. it doesn't inject wait semantics into custodian, its merely config for the lambda. there's a separate pr that I recently merged that handles dynamodb create events specifically since this has been a common use case by sleeping till the table is ready up to the time lambda timeout. also rather then commenting on a closed unrelated issue, its probably best to file a new issue.

**Comment by kapilt** [comment]
re which recent pr https://github.com/cloud-custodian/cloud-custodian/pull/3516

**Comment by tmxak** [comment]
thank you @kapilt 
Waiting for the release then!
