### ISSUE TITLE
bad docs in skip-ami-snapshots filter

### ISSUE THREAD

**Issue by arunakalla** [capitalone/cloud-custodian#1275]
when used in the policy it gives following error
LexerError: Bad jmespath expression: Unknown token '-':

policy snippet:
  - name: delete-ebs-snapshots-test
    resource: ebs-snapshot
    filters:
      - type: age
        days: 90
        op: ge
      - skip-ami-snapshots: False

**Comment by arunakalla** [comment]
above those dots are in fact '-'  dashes

**Comment by arunakalla** [comment]
in the custodian code example.. name of the resource is mentioned as 
resource: ebs-snapshots  (wrong)

resource: ebs-snapshot (correct)

**Comment by arunakalla** [comment]
I think error is because in schema we are validating for javascript boolean which expects lowercase true or false and in the validate we are checking for Python bool which expects (True or False)

    schema = type_schema('skip-ami-snapshots', value={'type': 'boolean'})

    def get_permissions(self):
        return AMI(self.manager.ctx, {}).get_permissions()

    def validate(self):
        if not isinstance(self.data.get('value', True), bool):
            raise FilterValidationError(
                "invalid config: expected boolean value")
        return self

**Comment by kapilt** [comment]
thats because your policy isn't valid. the policy the filter for skip-ami-snapshots is wrong as documented in the class doc string, see a good example here https://github.com/capitalone/cloud-custodian/issues/1254 @joshuaroot added some bad inline docs a while back that we've been incrementally cleaning up, pull requests welcome.
