### ISSUE TITLE
Feature Request - add way to ship the `notify` to elasticsearch

### ISSUE THREAD

**Issue by alfredgamulo** [capitalone/cloud-custodian#1613]
Already WIP: https://github.com/capitalone/cloud-custodian/pull/1612

The purpose of this feature request is to collect the data from the `notify` action into desired endpoints whether it be elasticsearch or logstash or any future endpoint. This will enable users that want to create a dashboard of resources surveyed and actions taken. 

@kapilt, right now it is an amalgamation of the indexer and mailer. The pattern for use would be to have `notify` send to SNS for fanout to the mailer SQS and this dispatcher SQS. 

I didn't think it would be a good idea to burden either existing tool with a refactor that generalizes the purpose of either one. My thoughts are that eventually people may want to migrate their mailer implementations to use this tool rather than add elasticsearch indexing into the mailer tool.

**Comment by kapilt** [comment]
why not just add an sqs subscriber to the extant indexer instead of duplicating it?

**Comment by kapilt** [comment]
the mailer already has an sqs subscriber, dispatching in this context is notifying to an sns topic and subscribing an sqs queue consumer for the functionality of interest.

**Comment by alfredgamulo** [comment]
Whatever we end up naming it, I think it would be better to create a new tool for this purpose and eventually migrate the mailer functionality into it. I think that putting this feature request into the mailer would be a schema breaking change for existing users and would be confusing under the "mailer" namespace

**Comment by kapilt** [comment]
this doesn't have anything to do with the mailer or a new tool though, it has to do with not trying to multiplex on sqs, and instead setup sns as a pub/sub for dispatching. then individual tools that  want to consume just hook to their own sqs queue. thats alot better than trying to reimplement broadcast logic and all of the tools in yet another tool. ie. think microservices on the downstream not monoliths and use the platform features instead of reimplementing.
