### ISSUE TITLE
sns topic - cross-account filters throwing false postivies results 

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#2027]
#### When an SNS topic has conditional statement like below, the Topic is flagged for cross-account access event hough the source account is matching from the account.json file.

```
{
    "Sid": "__console_sub_0",
    "Effect": "Allow",
    "Principal": {
        "AWS": "*"
    },
    "Action": [
        "SNS:Subscribe",
        "SNS:Receive"
    ],
    "Resource": "arn:aws:sns:us-east-1:xxxxxxxx:topicname",
    "Condition": {
        "StringEquals": {
            "AWS:SourceOwner": "123456789"
        },
        "StringLike": {
            "SNS:Endpoint": "*@foo.com"
        }
    }
}
```

Policy

```vars:
  accounts_url: &accounts_url accounts.json


policies:

  - name: sns_cross-account
    resource: sns
    filters:
      - type: cross-account
        whitelist_from:
          expr: "accounts.*.accountNumber"
          url: *accounts_url
```

#### error message

> no handler:handle_sns_endpoint op:StringLike key:sns:endpoint values:(u'@foo.com',)
> no handler:handle_sns_protocol op:StringEquals key:sns:protocol values:[u'email', u'sqs', u'lambda']

**Comment by alfredgamulo** [comment]
@kapilt bringing the discussion back here.. how exactly should this particular case be handled? Examine the other condition keys and see if `aws:sourceowner` is present if `self.allowed_endpoints` is empty? here: https://github.com/capitalone/cloud-custodian/pull/2028/files#diff-2feddf2e9868d5f513a284d116cdd2eaR63 
This would work better if the conditions list were passed instead of the full statement to the `handle_*` methods.
