### ISSUE TITLE
I want list of security groups which are linked with more than one resource. 

### ISSUE THREAD

**Issue by dharaghodasara** [capitalone/cloud-custodian#2052]
I need some way through which i can filter those security groups which are used in multiple resources. Based in our security policy, we need to use separate security group for each resource. 

Can you please provide a way to do this?

**Comment by kapilt** [comment]
we generally support querying a resources security group to find interesting matches, ie resource -> sg style filters. For security group to resource we don't generally support that because a group can be attached to many different types of resources. a notion of one group per resource doesn't generally scale.
