### ISSUE TITLE
Design Events Implementation

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2213]
Design the Azure equivalent to the AWS Lambda support
http://capitalone.github.io/cloud-custodian/docs/policy/lambda.html

It has been proposed that this could be done with 

Activity Logs -> Event Hub -> Azure Function 

or potentially

Azure Monitor Alerts -> Azure Function (However it is unclear if Azure Monitor Action groups have a reliable and secure way to call a function yet)

This issue should track the proposed design and agreement, and then we'll file issues to track implementation tasks.

**Comment by kapilt** [comment]
We'll also need a variant of mu for cloud functions. I think we'll need to move policy execution modes to using a registry as well, and update schema for that.

On the overall subscription, the ideal scenario minimizes both the invocations of functions to just the events of interest, and secondarily that we not even process events not of interest.

Given that, the issue i think with activity logs -> event hubs -> functions is that we have to replay the entire volume of activity logs to event hubs, it was unclear if we could filter the activity log stream till we got to the hub -> function subscription. If there is then that would be ideal.

Azure monitor alerts seem to handle that filtering within their definition but as you note its unclear if there is a direct invocation mechanism there for function invocation.

Outside of feature dev by the underlying product teams, ie. based on what we have now, the path forward is still activity log -> hub - function.

I'd suggest we start with just provisioning the cloud function as a minimal work stream thats common to all approaches, and can then re-evaluate as there is product evolution.

**Comment by aluong** [comment]
Azure Functions support of Python appears to be moving in the direction of using containers with a python virtualenv. I am capturing some notes on items that will need to be investigated.

- [ ] Python Runtime Dependencies: Python virtual env needs to be compatible with the custodian application dependencies and the azure functions runtime dependencies. In particular, the large Azure python SDK.

- [ ] Identity + Auth: We need to provide environment variables to the Azure function with the credentials of the service principal. It would be even better if we could use [MSI](https://docs.microsoft.com/en-us/azure/app-service/app-service-managed-service-identity) for the identity of the function app. (may need to add explicit support for this in custodian)

- [ ] Packaging and Uploading: Wrap or leverage existing mu.py to create packages. Either the custom policy needs to be built into a new container image or it needs to be uploaded via Kudu to the function app.

- [ ] Caching Azure Dependencies between multiple lambdas because of large Azure function dependencies. (This may not be an issue if we are leveraging containers and we have a base image with all of the dependencies)

**Comment by stefangordon** [comment]
Closing this abstract level work item - we have more tactical work items in place or coming for remaining work.
