### ISSUE TITLE
SendGrid based Notify action for Azure

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2236]
Note the existing `c7n\actions.py` `class Notify(EventAction):` 

SendGrid is nicely integrated into Azure and the most common/easy way to support email.  Let's figure out how to wire up a notifier action for Azure that uses SendGrid.

Consider if we should make it somewhat generic so that we can support destinations other than email, such as event hubs or queues.

**Comment by thisisshi** [comment]
The work being done to add Slack as a delivery mechanism is currently being worked on here: https://github.com/capitalone/cloud-custodian/pull/2224 which is similar to this. Datadog transport was recently added to c7n_mailer as well (https://github.com/capitalone/cloud-custodian/pull/2197). I think the only thing that really needs to change is the transport method, rather than pointing at SNS or SQS we can add the option to point at SendGrid

**Comment by kapilt** [comment]
ideally we'd keep the send grid integration in mailer, and add one of the azure centrics transports for delivery to the mailer, alot of our rendering / contact address lookup is based in the mailer. notify is basically a data publishing mechanism via pluggable transport.

**Comment by stefangordon** [comment]
That definitely makes sense.

**Comment by stefangordon** [comment]
#2429 will resolve half of this
