### ISSUE TITLE
Investigate Azure Dev Test Labs for Functional Tests

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2243]
Azure Dev Test labs seems like it may provide useful benefits in automating the provisioning and cleanup of resources for recording test cassettes or live functional tests.

https://docs.microsoft.com/en-us/azure/devtest-lab/devtest-lab-overview

You'd define ARM templates to represent the test environments, but it helps with cleanly provisioning the environment for a test run and cleaning up afterward to control costs.  It also knows how to read templates directly from source control and integrate with CI/CD pipelines.

My main priority right now is in the easiest way to ensure developers can reliably deploy environments to reproduce/record all our VCR tests (from their desks, not in automated build pipelines).  This may be a cleaner approach than manually coding resource provisioning into tests.

**Comment by kapilt** [comment]
the devtest lab seems rather vm centric in reading through the docs, ie. whats the delta on test setup/teardown of an arm template vs using devtest-lab?. we've tended to be api centric around resource construction with functional decorator on test contained resources/contexts, but we tend to do those on resources that are relatively fast to provision, and defer to pre-existing context for slower resources. another notion here might be a `@arm_functional` which takes an arm template as reference for the test execution. most of this is a balance against time to test and execute, and a desire to keep feedback loops short. we did consider cfn for aws resources but it was typically multi-minute latency adds for resources that would otherwise be fast (seconds) to create/destroy.  Another thought if we want to go down a declarative road is considering terraform on resource provisioning in that it gets to a baseline cross cloud addressable tooling.

**Comment by stefangordon** [comment]
It does have VM specific behavior for simple app testing but also supports defining full environments through ARM templates.  If you are going to use ARM templates to deploy this gives you a very clean interface where each test environment is considered a tracked unit, and you simply create/enumerate/delete environments with a single API call.

https://docs.microsoft.com/en-us/rest/api/dtl/environments

Agreed ARM template may not be the way to go though, we'll use this task to research options and flush out a plan/work items.

**Comment by stefangordon** [comment]
Oh @kapilt to clarify, I see how you approach `@functional` in AWS but it isn't clear to me how I would regenerate everything in the `tests\data` folder for the non-functional tests.  Is that possible?

That is the scenario I was targetting here - the ability to create a significant number of resources to be able to regenerate cassettes for the entire set of Azure tests with a single command. 

In terms of functional/live tests meant for people to actually run frequently, I agree ARM deployments would be pretty slow.

**Comment by stefangordon** [comment]
#2269 resolves this for now, I don't think dev test labs is needed for unblocking this issue.  Closing.
