### ISSUE TITLE
EC2 filter for instances launched in public subnet

### ISSUE THREAD

**Issue by davidclin** [capitalone/cloud-custodian#2257]
Hi, I'm new to Cloud Custodian and am really liking it. Is there an example of how to filter for EC2 instances that get launched in a public subnet then get notified by email and/or SMS?

**Comment by thisisshi** [comment]
You can use the subnet filter to filter ec2 instances based on the subnet they're attached to:

```bash
$ custodian schema ec2.filters.subnet
```

As for the notification, you can use the notify action and use c7n_mailer to ship the message to email or SNS

**Comment by kapilt** [comment]
alternatively filter for instances with public ip (note you need to do this on the instance network attachments to catch all cases, ie secondary nic with public, for multi-homed instances)

**Comment by davidclin** [comment]
Thanks for the helpful suggestions!  Is it possible to filter for new ec2 instances that get launched versus all ec2 instances that have public ip's/subnets?  My use case is as follows. I have an AWS account I've inherited that have some ec2 instances in a public subnet/have public IP addresses. I don't want to touch those. However, for any new ec2 instances that get launched by users should be notified and the instance terminated.  Is this possible? (Aside, it took me some time to get the mailer working but I got it working. Hurrah!)

**Comment by kapilt** [comment]
There's a few different ways to achieve that 

- [ ] Use cloud watch events execution mode for the policy and target RunInstances, that will only operate against new instances.
- [ ] Use a filter on instance age so that you only target instances less than N days old.
- [ ] Use a filter that excludes the set of instances that you don't want to target, ie a value filter with value_from that pulls a json file from s3 with instance ids you don't want the policy to touch.

**Comment by sadik13** [comment]
Hi, I'm new to Cloud Custodian. i want to Create policy to check public IP of EC2 instance in aws by using cloud custodian.
So, some one can help me for this code samples.

Thanks in advance.
