### ISSUE TITLE
c7n_mailer lambda error after included slack integration

### ISSUE THREAD

**Issue by felipefsso** [capitalone/cloud-custodian#2306]
Hi team,

It appears that deployed lambda mailer is having some problem with the libs, after the last commit that included slack integration. 

After update c7n_mailer lambda I'm seeing this error in the logs:
```
[ERROR] 2018-05-01T00:45:26.698Z f04d1326-4cd8-11e8-9f05-670c91cd10c1 Error starting mailer MailerSqsQueueProcessor().
Error: No module named requests

Traceback (most recent call last):
File "/var/task/c7n_mailer/handle.py", line 46, in start_c7n_mailer
mailer_sqs_queue_processor.run(parallel)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 126, in run
self.process_sqs_message(sqs_message)
File "/var/task/c7n_mailer/sqs_queue_processor.py", line 170, in process_sqs_message
from .slack_delivery import SlackDelivery
File "/var/task/c7n_mailer/slack_delivery.py", line 17, in <module>
import requests
ImportError: No module named requests
```
 I've had no success even with a fresh install from the repos.

**Comment by LykinsN** [comment]
https://github.com/capitalone/cloud-custodian/pull/2307 I've opened a new PR to include this dependency.

**Comment by LykinsN** [comment]
Can you confirm whether this change resolves the issue you're seeing?

**Comment by kapilt** [comment]
the pr is unrelated to the solution for the problem, pip does install recursive dependencies, I'll have another pr up shortly.

**Comment by kapilt** [comment]
I was chatting with @felipefsso about this on gitter yesterday, the root of the issue is that lambda dependencies need to be specified specifically in deploy, in addition to specifying in package deps. Its important to note requirements.txt dependencies are primarily for ci, for distribution setup.py deps are primary, and for self-provisioning lambdas those dependencies need mirroring into lambda provisioning code. I've added an explicit additional warning to setup.py requirements for future modifiers.
