### ISSUE TITLE
Azure - Run policy across multiple subscriptions

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2309]
Either by enumerating subscriptions for the Account object, or by providing a list of subscriptions.

There is related functionality for AWS.  Need to research/evaluate what features exist for C7N in AWS and create work items to implement parity in Azure.

**Comment by kapilt** [comment]
so we currently use tools/c7n-org to run across multiple accounts. there's a script in that directory to generate multi-account config from a separate orgs api. the nice part of it is that does a good job dealing with concurrency via multi-process exec. i've noodled on having some notion of invoke policy action on an account resource within a policy, but there's a couple of reasons to favor a separate front end for the multi-subscription execution, better concurrency mgmt, better awareness on reporting, easier policy file resolution, etc. might be a good topic for the sprint discussion, anyways on parity aspects for c7n-org we would need to distinguish between types of cloud accounts in the accounts config schema, and also potentially a mechanism to generate that file from an api. this also comes up in gcp, where project == account id == subscription for common terms as a root level holder for resources, gcp though has its ARM hierarchy done at the project level rather than within a subscription, which needs accounting for. for aws accounts gen from org api, i ended up encoding logical hierarchy of accounts into account tags.

**Comment by tbarlow12** [comment]
@kapilt are there any docs available for c7n-org?

**Comment by stefangordon** [comment]
tools/c7n_org/README.md
