### ISSUE TITLE
Azure - Plan to start publishing c7n_azure to PyPi

### ISSUE THREAD

**Issue by stefangordon** [capitalone/cloud-custodian#2499]
Need to sync with @kapilt to see how we want to manage this.  I can do it or there may be an existing process we should fall into.

**Comment by kapilt** [comment]
I actually just pushed trunk of c7n_azure over to pypi for 0.1 version, to support the the Mailer dep. We should sync up release mechanisms, I'm open to all options. At the moment given the mono repo, for custodian releases, i tag the repo against the main c7n version and release all the tools/* with updates since the last release.

**Comment by stefangordon** [comment]
That sounds great.
