### ISSUE TITLE
Offhour Policy

### ISSUE THREAD

**Issue by Dhariaj** [capitalone/cloud-custodian#2584]
Wondering what people have done to sort this issue.. We have custodian policy that powers off instances at 8pm and powered the back on at 8am only Monday-Friday. it appears to working fine during weekdays but doesn't always power on Monday morning.  The Filter within the start up policy is 

    - type: value
        value: 1
        key: LaunchTime
        op: less-than
        value_type: age
and I took the policy from https://www.capitalone.io/docs/usecases/ec2offhours.html#ec2offhours Is there a work around?

**Comment by thisisshi** [comment]
if you're filtering on `LaunchTime`, and the instance has been off since friday it should be at this point greater than 1 day. You should use the dedicated onhour/offhour filters/actions docs: https://capitalone.github.io/cloud-custodian/docs/quickstart/offhours.html

**Comment by Dhariaj** [comment]
I am using dedicated tags. at this moment I am using StartAfterHours: on=(M-F,8) to power on my instances. I can remove the 1 day filter and try..

**Comment by thisisshi** [comment]
You shouldn't need to define the LaunchTime filter unless you're only trying to filter in resources that have been started within the last day, since you're not turning instances on during the weekend, each monday all of your instances will have launch times > 1 day. There are definitely valid use cases for only filtering instances with launch time < 1 day, i.e. not turning on instances that have been purposefully shut down for long periods-- but for most environments I would imagine that the filter wouldn't be needed.

**Comment by Dhariaj** [comment]
Thank you.
