### ISSUE TITLE
sleep filter to allow for lambda tag compliance on resources which async tag

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#262]

**Comment by kapilt** [comment]
i have a lot of mis-givings about supporting this, use case was lambdas on ec2 doing tag compliance, its implemented, but i think the right approach is going to be support config rules which has a built in delay.

**Comment by caversa** [comment]
Kapil,

I see this issue is closed - did the sleep get implemented?  I have this exact same scenario, as I was really liking tying tag compliance to CloudTrail, but the evaluation of the tags is happening a little too quickly.  We use Terraform to provision our instances, and although the tagging happens in milliseconds, I am finding that roughly half the time the tags are in place, and half the time they are not yet in place when the Lambda function fires.  I can switch to polling every hour, but would definitely be interested in your thoughts on the matter before I do so, since having a resource immediately shut down that isn't properly tagged is definitely my ideal.

Thanks,
Carrie

**Comment by kapilt** [comment]
it was implemented, and removed shortly there after due to misgivings about that behavior. Trying to avoid races by sleeping doesn't really feel appropriate, its a works for sunny weather behavior, but breaks when there's any issue or problem on the service or automation then delays increase and the custodian policy then triggers and intensifies the problem. Fwiw, I've observed multi-minute delays with cloudformation tagging ec2 instances on busy accounts.

the recommended alternative would be to use a config-rule which gives additional latency on a 15m basis, but still using lambda.

on your policy you can just add

```
mode:
  type: config-rule
```

and possibly role: lambda_exec_role if your not using   


the other recommend is to separate out ec2 instances being created by user automation, vs that being created by autoscale groups, and other services, and for the later to do tag enforcement directly on the higher level service resource creation (asg, emg, etc) where possible (create call supports tags).

**Comment by caversa** [comment]
I switched the mode to config-rule, and it is working very well!  Thanks for the great advice!  Glad the solution was so clean!

Carrie

**Comment by tleyden** [comment]
> it was implemented, and removed shortly there after due to misgivings about that behavior. Trying to avoid races by sleeping doesn't really feel appropriate, its a works for sunny weather behavior, but breaks when there's any issue or problem

I agree 100% -- I think the the 12 factor app should be renamed to the 13 factor app:

**13. Never, ever, ever use sleep() to avoid race conditions!** 😴
