### ISSUE TITLE
Caught Error Allows For Continuation Instead of Exiting

### ISSUE THREAD

**Issue by cpgravlee** [capitalone/cloud-custodian#2824]
Hello,

I recently ran into an issue where my policy, which is checking the tags on S3, deleted the bucket even though the tags were correct.  After consulting the logs, I found `"unable to invoke method:get_bucket_tagging error:We encountered an internal error. Please try again."`.  This in isolation is not an issue, but the code found here: https://github.com/capitalone/cloud-custodian/blob/master/c7n/resources/s3.py#L445 didn't actually stop custodian from progressing to the actions of the policy.  The actions are set to "remove-contents: true" & "delete".  Because of this, my bucket was deleted and the contents removed even though it was in-policy.  Is this going to continue to be the action going forward, or would you be open to a PR that allows it to fail hard instead of allowing the actions to occur?

**Comment by FireballDWF** [comment]
In other words, the desired behavior is for Cloud Custodian to fail the policy execution thus not take any action if an AWS API call fails.

**Comment by kapilt** [comment]
noted and agreed, the s3 api experienced an incident for a few hours yesterday on tag management. agreed we should just fail hard on unknown error. I'll send a pr in a few minutes.

**Comment by cpgravlee** [comment]
Thank you for doing that.  Are there any other resources that have this same issue?

**Comment by kapilt** [comment]
none that come to mind, we default to raise on unknown as general practice, s3 was special cased due to a lot of variation on bucket policies that caused denials when processing the entire accounts buckets. note we are retaining the continue on auth denied error, policies that depend on augmented fields should generally check for the denied methods annotation, its generally not a concern as lockouts are typically carte blanche, but its good to be aware of.  https://github.com/capitalone/cloud-custodian/pull/2826/files
