### ISSUE TITLE
Ability to select fields while using report

### ISSUE THREAD

**Issue by kumarsiyer** [capitalone/cloud-custodian#471]
Can you include the ability to select fields while using the custodian report. Currently there is no way a user can specify the fields required for output to csv.

**Comment by kapilt** [comment]
sounds good, at the moment our reports have some org specific tag structure to them. i think we need both adhoc cli extension of attributes in the report, and some config based format. For column definition in the csv, i'd like to leverage a key=jmespath  style syntax. so
```
custodian report --field="size=Size"
```
as an optimization it would be nice to eval the expression against the record collection instead of individual records, but that might be premature and automatable (expr preprend [].)

**Comment by scotwk** [comment]
@kapilt - implementation questions

I assume you could specify `--field` any number of times to include multiple fields (correct?).  Questions:

1) If a user specifies some number of fields using --field, should the set of fields included be limited to just what the user specifies, or are there any fields that should always be included, such as the instance ID?

e.g. If a user specifies `--field foo` and `--field bar`, the CSV will have two columns, `foo` and `bar`

2) The report currently includes information from the tags.  Should there be a way to specify fields from the tags as well?  This could be a different flag such as `--tag-field="name"` or we could have a special prefix in the field name that indicates it is a tag such as `--field="tag:name"`

**Comment by kapilt** [comment]
i think we should retain the intrinsics unless a user specifies via option otherwise (--no-defaults), we also want to preserve order on the user specified options. we're currently got some org specific stuff on tags that needs pulling ideally as its org specific (OwnerContact, etc). 

2) We should have helper syntax for tags, i'd go with --field="tag:name" there's some stuff.

Other stuff to consider but not required, putting the default format spec on the model for each type, it already includes id/name fields. reusing value filter for expression retrieval, probably overkill.

**Comment by scotwk** [comment]
@kapilt 

I've completed this work for the `report` subcommand on my local branch.  I'll commit and push it shortly and provide you a link in slack to review.  I didn't create a PR yet in case you wanted to change any of my approach which I detailed below.

`--field` support two types of entries:

* Giving a prefix of `tag:` will search the tags for the provided key.  E.g. `tag:CustomId` will find the `CustomId` tag.
* Any other expression will be evaluated as a JMESPath expression against the resources.json dictionary.

Fields are added in the same order they are specified on the command line, and they are added to the end of the CSV file, except if `--no-default-fields` is specified, in which case the default format spec is not included.

I did *not* allow for the `size=Size` style of syntax which you mentioned above.  I assume the first part is to set the header name?  I was worried about cluttering the user interface.  (Would the corresponding entry for tags be `size=tag:MySize`?  Would the default if no `=` sign is included be to just use the field name as the header name?  That's what I do now - I just use the name of the field for the header)  If you think this is essential its not hard to put in - I was just trying to keep the UI cleaner.

I do not have any unit tests yet, but based on the coverage I don't think there are any unit tests for the `report` subcommand.  Do you need tests before creating a PR?  Do you need tests for the entire `report` subcommand - and is that something that we should be working on?

As for the other things you wrote above - I'd need some more details.  Which model are you referring to in "putting the default format spec on the model for each type"?

**Comment by kapilt** [comment]
@scotwk cool.

wrt to size=Size, i guess the issue is that jmespath expresssions can get quite complex and we need some sort of relabel for complex expressions, ie. here's one that got handed to me in slack yesterday "max([].length(TargetHealthDescriptions))" (app elb). Re clutter, i think its fine if its optional, but that can be a followup.

wrt to tests, definitely would appreciate a test before *merge*, in part because of the lack of them to date in the reporting code. if you want to send the pr for initial review comments prior that's fine as well.

wrt to models, 99% of the resources are based on `skew` library's models, potentially with augmentations that we do for various things, rather than having a bunch of formatters divorced of the model definitions, it would be nice to just co-locate those with the model. as an example see the resources/efs.py. ie. we have some generic name/id fields for any given resource there, putting the default format for a resource on to those will allow more ready reuse in different front ends. again its deferrable, just noodling on what ideal target looks like.

**Comment by scotwk** [comment]
@kapilt 

Good point on the complex expressions.  I'll add in the ability to set the header tonight and submit a PR.  I am traveling thru the weekend and don't have time to write tests, but I'll pick that back up next week.

**Comment by scotwk** [comment]
@kapilt - Tests are added.  The PR is passing all tests.  I can look at moving the models next if you think that takes priority over other work.  But if you have users wanting this feature then I think this can be taken as-is and that can be a next step.

**Comment by scotwk** [comment]
@kapilt - This has been released and I think this issue can be closed.

**Comment by kumarsiyer** [comment]
Yeah thanks @scotwk and @kapilt I have already tested this 👍
