### ISSUE TITLE
generic resource support on csv report

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#648]
we want to support all the resources that custodian supports. so deferring to our meta model (skew) for default csv resource fields. if no default defined, name, id, date fields (later if present, former). yank any default tag fields besides name.

**Comment by skurfer** [comment]
Skew seems to have very little to say about the information available for resources. Did you have any examples of default fields available from Skew (other than ID)?

Failing that, do you think it would make sense to move the formatters into their respective files in `resources` so all the resource-specific behavior is at least in one place? We could also add some lookup mechanism in favor of the current hard-coded dictionary.

**Comment by kapilt** [comment]
id and name are all skew has by default, i'm suggesting extending the models within custodian wrt to defining a resource specific default set of fields for the csv reports. as example of other extensions we've done to the model, config rule support has model info.  i'm trying to find some time to chat with skew author at reinvent this week to see if we can upstream some of this stuff.

**Comment by skurfer** [comment]
So just relocate the defaults to each resources `resource_type` class? Using RDS as an example, something like

```python
class resource_type(rds.DBInstance.Meta):
    filter_name = 'DBInstanceIdentifier'
    config_type = 'AWS::RDS::DBInstance'
    report_fields = (
        ('instance id', 'DBInstanceIdentifier'),
        ('db name', 'DBName'),
        ('creation time', 'InstanceCreateTime'),
        ('encrypted', 'StorageEncrypted'),
        ('publicly accessible', 'PubliclyAccessible'),
    )
```

That would tell us the human readable header for the report, and the key containing the information.

Let us know if that’s the right general direction.

**Comment by kapilt** [comment]
thats the direction, though wondering if we should just drop the title fields and keep a list of attributes, its human interpretation, and we should let the end user reformat/flow to target.

**Comment by skurfer** [comment]
On some resource managers, the `resource_type` property is just a string. On others, it’s a class inheriting from `object`, and on others it subclasses something entirely different.

I want to assign properties for the ID field and default fields to the `resource_type`, which won’t work if it’s a string. Is it as simple as removing the string and subclassing `ResourceQuery.resolve(<string value>)` as in the S3 resource, or will that break things?

Another option might be to just stick the properties on the resource manager class itself instead of on the `resource_type`. I think that’s what I’m leaning towards. Thoughts?
