### ISSUE TITLE
debug pypy memory leaks with pypy upstream

### ISSUE THREAD

**Issue by kapilt** [capitalone/cloud-custodian#761]
when we've used pypy with custodian for long running operations (s3 scans) we get significant performance boosts, but accompanied by signficant memory growth, i strongly suspect we could probably reproduce this standalone, and the cause is likely the dynamic class construction of the sdk, which we should try and get to standalone reproducible case for discussion with pypy upstreams.

just creating a session / client / and doing an api call in a loop should be a good start for standalone reproduction.

**Comment by skurfer** [comment]
Have a look at this @kapilt 

https://gist.github.com/skurfer/41f99002f56f4a1c2f76fdf32e711351

There are some small reproducible leaks from that (in both PyPy and C Python), but if you know of some code that would better demonstrate the problem, let me know.

**Comment by kapilt** [comment]
you'll need probably at least one maybe two orders more magnitude.

**Comment by kapilt** [comment]
here's a standalone example of the pypy memory leak, needs a big bucket with a few million objects to exhibit
https://gist.github.com/kapilt/b2550e6b36da5650230a763268e3bd0a

**Comment by kapilt** [comment]
and it looks like the root of the issue is creating and using boto3.Sessions, switching out to reusing a client in separate threads seems to work well to avoid the memory leak.

**Comment by gfranxman** [comment]
I've hammered on this from a number of angles.   
The leak in your example occurs at the line:
~~~
info = client.head_object(Bucket=bucket, Key=k['Key'])
~~~
But you can trigger it with even simpler interactions, like:
~~~
getattr(client, 'meta' )
~~~
This applies to nearly any attribute of the client.
However, calling getattr to get the _cache or _class do not trigger the leak (maybe a clue?)

I believe the issue is somewhere inside the botocore.client.ClientCreator.     Initially I was convinced it was the _create_api_method creating closures shared between the Creator and the constructed class, but creating a dummy script that does the same thing doesn't exhibit the same leak.
 
If not there, then I'm suspicious of the Session class's SESSION_VARIABLES class attribute.   I'm not certain that class vars are thread safe, and I note they are using shallow copies which would seem to defeat the purpose.

**Comment by kapilt** [comment]
hmm.. thanks i guess the question is does this reproduce on cpython, if so then a bug on boto, if not we should file against pypy upstream.
