### ISSUE TITLE
Allow notifications coming out of custodian to be put into slack channel

### ISSUE THREAD

**Issue by mandersen94** [capitalone/cloud-custodian#890]
More details to come.  our team is interested in doing the dev on this.

**Comment by kapilt** [comment]
could go as another transport for notify, but will also need to do some default formatting inline. alternatively as a delivery mechanism for mailer which would allow some formatting. what sort of output are you thinking about in the slack channel?

**Comment by caversa** [comment]
We have the same need, but I'm handling it by adding the to: to an SNS topic, and then using the AWS built-in Lambda blueprint to create the integration between Slack (the blueprinted Lambda function is a subscriber to the topic) .  

If you try this route, something I wanted to mention... I have noticed that to get SNS to work I needed to populate the cross-account mail setting, even though I'm doing everything within the same account.  Otherwise I get an error.

role: arn:aws:iam::foobar:role/cloud-custodian
cross_accounts:
  'foobar': 'arn:aws:iam::foobar:role/cloud-custodian'

**Comment by mandersen94** [comment]
Let me try the SNS / Lambda Slack Blueprint route mentioned first. Might fit the bill without adding Slack specific features.

**Comment by kapilt** [comment]
while i'm game for direct slack integration.. routing through the mailer to sns might be a better option in terms of giving formatting control with template rendering, the notification action is really a data transport at the moment.

wrt to why on the cross accounts, i think just because its marked as required in the jsonschema for the mailer config.

another option on slack relaying without the mailer indirection is invoke-lambda.

**Comment by mandersen94** [comment]
We are good with the SNS -> Lamba Slack approach and proved it out for another need.  Fits better into the serverless / micro building blocks approach.  I'm closing this.
