### ISSUE TITLE
Global grants should allow choosing read and/or write

### ISSUE THREAD

**Issue by jeffastorey** [capitalone/cloud-custodian#97]
The global grants filter should be configurable as to whether you're checking read and/or write. In some cases, we want to allow global reads for example, but not global writes.

**Comment by kapilt** [comment]
if the use case for global-reads is website hosting, they should configure the bucket as a website, which will remove it from being considered a global read access system. in general i think any such global-reads for non website should be considered as a recorded exception via filter, rather than blanket allow by letting them go through.

**Comment by jeffastorey** [comment]
The issue here is that when you add an exception, you add it for all global grants. It would be useful to have exceptions specifically for read or writes. One thought is to have the policy configured so you can say whether you're configuring enforcement of global reads, writes or both (default). Your yaml could have 2 policies - one for read, one for write - and you could have different exceptions for each.

**Comment by kapilt** [comment]
makes sense and sounds good.

**Comment by kapilt** [comment]
merged
